services:
  api-solid-pg:
    image: bitnami/postgresql
    container_name: todo
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=itudb
